package com.example.applicationvault.navigation

const val ROUTE_REGISTER = "register"
const val ROUTE_SPLASH = "splashscreen"
const val ROUTE_EMPLOYER_REGISTER ="employerscreen"
const val ROUTE_EMPLOYEE_REGISTER =  "employeescreen"
const val ROUTE_EMPLOYER_LOGIN = "employerLoginscreen"
const val ROUTE_EMPLOYEE_LOGIN = "employeeLoginscreen"
const val ROUTE_IT = "IT"
const val ROUTE_EMPLOYER_HOME = "employerhomeScreen"
const val ROUTE_TEACHING = "teaching"
const val ROUTE_MANAGEMENT = "management"
const val ROUTE_HEALTH = "health"
const val ROUTE_MEDIA = "media"
const val ROUTE_ENGINEERING = "engineering"
const val ROUTE_EMPLOYEE_ENGINEERING = "employeeengineeringScreen"
const val ROUTE_EMPLOYEE_TEACHING = "employeeteachingScreen"
const val ROUTE_EMPLOYEE_HEALTH = "employeehealthScreen"
const val  ROUTE_EMPLOYEE_MEDIA = "employeemediaScreen"
const val ROUTE_EMPLOYEE_MANAGEMENT = "employeemanagementScreen"
const val ROUTE_EMPLOYEE_IT ="itemployeeScreen"
const val ROUTE_EMPLOYEE_HOME = "employeehomeScreen"
const val ROUTE_VIEW_EMPLOYEE = "employeeviewScreen"
const val ROUTE_VIEW_EMPLOYER = "employerviewScreen"
const val ROUTE_UPDATE_EMPLOYEE = "employeeupdateScreen"
const val ROUTE_UPDATE_EMPLOYER = "updates"
const val ROUTE_VIEW_JOBS = "jobs"
const val ROUTE_APPLY = "apply"